title: JAR Template
description: A simple and powerful VexCode library featuring PID, odometry, and custom motion algorithms.
theme: just-the-docs
color_scheme: dark

url: https://2775josh.github.io/JAR-Template/

aux_links:
  Download JAR-Template: <a href="https://github.com/2775Josh/JAR-Template" target="_blank">

plugins:
  -jekyll-tabs

search_enabled: true

search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true
