title: JAR Template
description: A simple and powerful VexCode library featuring PID, odometry, and custom motion algorithms.
theme: just-the-docs
color_scheme: dark

url: https://2775josh.github.io/JAR-Template/

aux_links:
  Github: https://github.com/2775Josh/JAR-Template
